services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: blog-app-dev
    container_name: blog-app-dev
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
      - "${VITE_PORT:-5173}:5173"
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_URL=${APP_URL:-http://localhost:8000}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - RUN_MIGRATIONS=${RUN_MIGRATIONS:-true}
      - RUN_SEEDERS=${RUN_SEEDERS:-false}
      - COMPOSER_ALLOW_SUPERUSER=1
      - VITE_HMR_HOST=${VITE_HMR_HOST:-localhost}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - blog-network
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - ./storage/app/public:/var/www/html/storage/app/public
      - ./storage/logs:/var/www/html/storage/logs

  db:
    image: mysql:8.0
    container_name: blog-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-laravel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_password}
    volumes:
      - blog-db-data:/var/lib/mysql
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-root_password}"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  blog-db-data:
    driver: local

networks:
  blog-network:
    driver: bridge