version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-app
    container_name: blog-app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - RUN_MIGRATIONS=true
      - RUN_SEEDERS=false
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - blog-network
    volumes:
      - ./storage/app/public:/var/www/html/storage/app/public
      - ./storage/logs:/var/www/html/storage/logs

  db:
    image: mysql:8.0
    container_name: blog-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-laravel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_password}
    volumes:
      - blog-db-data:/var/lib/mysql
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-root_password}"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  blog-db-data:
    driver: local

networks:
  blog-network:
    driver: bridge