FROM php:8.2-fpm

#
# system deps
#

RUN apt-get update && apt-get install -y \
    nginx \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git

# nodejs
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

#
# php extensions
#

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# nginx
WORKDIR /var/www/html

COPY ./docker/nginx.conf /etc/nginx/sites-available/default

COPY . /var/www/html

# permissions
RUN chown -R www-data:www-data /var/www/html

# expose ports
EXPOSE 80 5173

# dev server
CMD ["/var/www/html/docker/dev.sh"]